create database capstone;

-- 3. Inner Join for Order Details
--- Join orders, order_items, and products to display detailed line items
use capstone;
select o.order_id, o.order_date, p.product_name, oi.quantity, oi.list_price, oi.discount,oi.total_price
from orders o
inner join order_items oi on o.order_id = oi.order_id
inner join products p on oi.product_id = p.product_id;

-- 4. Total Sales by Store
--- Write a query to group sales (total_price) by each store_id
SELECT o.store_id, st.store_name,
    SUM(oi.total_price) as total_sales
from orders o
join order_items oi on o.order_id = oi.order_id
join stores st on o.store_id = st.store_id
group by o.store_id, st.store_name;
-- 5. Top 5 Selling Products
-- o Use ORDER BY and LIMIT to get the top 5 most sold products by quantity. 

select  p.product_name, 
    SUM(oi.quantity) as total_quantity_sold
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_id, p.product_name
order by total_quantity_sold DESC limit 5;

-- 6. Customer Purchase Summary
-------- o For each customer, return total orders placed, total items purchased, and total revenue. 

select c.customer_id,
    concat(c.first_name, c.last_name) as customer_name,
    count(DISTINCT o.order_id) as total_orders_placed,
    SUM(oi.quantity) as total_items_purchased,
    SUM(oi.total_price) as total_revenue
from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.customer_id, customer_name;

-- 7. Segment Customers by Total Spend
----- o Write a query to classify customers into spending brackets (e.g., low, medium, high). 

SELECT 
    o.customer_id,
    SUM(oi.total_price) AS total_spend,
    CASE 
        WHEN SUM(oi.total_price) >= 5000 THEN 'High'
        WHEN SUM(oi.total_price) >= 1000 THEN 'Medium'
        ELSE 'Low'
    END AS spending_bracket
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.customer_id;

-- 8. Staff Performance Analysis
-------- o Analyze total revenue generated by each staff member based on their handled orders. 

SELECT s.staff_id, 
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name, 
    SUM(oi.total_price) AS total_revenue_generated
from staffs s
JOIN orders o ON s.staff_id = o.staff_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.staff_id, staff_name
ORDER BY total_revenue_generated DESC;

-- 9. Stock Alert Query
-------- o Write a query to list products where stock quantity < 10 in any store. 

SELECT st.store_name, p.product_name, s.quantity AS current_stock
FROM stocks s
JOIN stores st ON s.store_id = st.store_id
JOIN products p ON s.product_id = p.product_id
WHERE s.quantity < 10;

-- 10. Create Final Segmentation Table
----- o Create a table customer_segments that will be populated from Python ML results later.

CREATE TABLE customer_segments (customer_id INT PRIMARY KEY,
    recency INT,
    frequency INT,
    monetary DECIMAL(10,2),
    segment_label VARCHAR(50),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id));



